### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by memetics19** [dataloop-ai/ZazuML#12]
Update the readme, couldn't able to run the docker image in the local.

Reproducing the issue: `docker: Error response from daemon: Unknown runtime specified nvidia.
`

**Comment by NoamRosenberg** [comment]
@memetics19 there may be an issue with your drivers. Where are you running the code? What OS? Do you have a GPU? Do you have nvcc installed?

**Comment by memetics19** [comment]
Ah! I see in this pc I don't have GPU, but I check in other PC. I'm using Fedora OS
