### ISSUE TITLE
ModuleNotFoundError: No module named 'zoo.convert2Yolo'

### ISSUE THREAD

**Issue by rajputnr** [dataloop-ai/ZazuML#2]
from zoo.convert2Yolo import convert
ModuleNotFoundError: No module named 'zoo.convert2Yolo'
**Help to resolve this problem.**

**Comment by NoamRosenberg** [comment]
Hi @rajputnr have you followed the instructions in the “quick start” section. It seems to me you may not have cloned the second repo in the instructions.
